# Generated by Django 2.0.4 on 2018-04-19 18:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RGBA'), size=None)),
            ],
        ),
    ]
