# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 10:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0022_rename_category_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='polis_id',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='polis_id',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='polis_slug',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='polis_url',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='polis_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='customizations',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Customizations'),
        ),
    ]
